"""Roadmap V5 Phase 1 — report determinism floor (+ the fix it caught).

The core deliverable a customer keeps is the report. Phase 1 added a
determinism floor and it immediately caught a real product bug:
mitigation / attack-path / structural-recommendation / fallback-threat
IDs were minted with ``uuid.uuid4()``, so analysing the SAME system
twice produced DIFFERENT reports — un-diffable (`atms diff`),
un-cacheable, and unsafe to reference an ID in a ticket.

Fixed in v0.19.1 by ``engines._ids.stable_id``: content-addressed IDs
that repeat across runs. This module pins:

  1. Every bundled sample's HTML + Markdown report is byte-identical
     across two analyse+render cycles, once the single intentionally-
     variable line ("Generated by ATMS v… on <timestamp>") is
     normalised.
  2. Artefact IDs (mitigations / attack paths / recommendations)
     repeat across runs.
  3. The ``stable_id`` helper contract.
  4. The ``_fallback_threats`` safety net is deterministic too.

Pure-IT samples (no AI component) are analysed with
``require_ai_components=False`` — the same auto-detect ``atms selftest``
uses. KEEP suite (flags off) — the shipping contract.
"""

from __future__ import annotations

import glob
import re
from pathlib import Path

import pytest
import yaml

from atms.engines._ids import stable_id
from atms.engines.ai_scope import find_ai_components
from atms.models import Component, System
from atms.reporting.html import render_html
from atms.reporting.markdown import render_markdown
from atms.workflow import analyze

ROOT = Path(__file__).resolve().parents[1]
SAMPLES = sorted(glob.glob(str(ROOT / "samples" / "*.yaml")))

# The only intentionally-variable content in a report is the
# generated-on timestamp. It appears in two forms (Markdown uses an
# "on" separator; HTML uses a unicode middot), so normalise the raw
# ISO-8601 timestamp wherever it occurs. Everything else must be
# byte-stable across re-analysis.
_ISO_TS_RE = re.compile(r"\d{4}-\d\d-\d\dT\d\d:\d\d:\d\d(?:[+\-]\d\d:\d\d|Z)?")


def _norm(text: str) -> str:
    return _ISO_TS_RE.sub("<ts>", text)


def _analyze(path: str):
    s = System.model_validate(yaml.safe_load(Path(path).read_text(encoding="utf-8")))
    has_ai = bool(find_ai_components(s))
    return analyze(s, require_ai_components=has_ai)


def test_samples_collected():
    assert len(SAMPLES) >= 10, f"expected >=10 samples, found {len(SAMPLES)}"


@pytest.mark.parametrize("sample", SAMPLES, ids=[Path(s).stem for s in SAMPLES])
def test_html_report_deterministic(sample):
    assert _norm(render_html(_analyze(sample))) == _norm(render_html(_analyze(sample))), (
        f"HTML report non-deterministic for {Path(sample).name}"
    )


@pytest.mark.parametrize("sample", SAMPLES, ids=[Path(s).stem for s in SAMPLES])
def test_markdown_report_deterministic(sample):
    assert _norm(render_markdown(_analyze(sample))) == _norm(render_markdown(_analyze(sample))), (
        f"Markdown report non-deterministic for {Path(sample).name}"
    )


def test_artefact_ids_repeat_across_runs():
    """Mitigation / attack-path IDs must be identical across two
    analyses of the same system — the v0.19.1 stable-ID fix."""
    a = _analyze(str(ROOT / "samples" / "rag_system.yaml"))
    b = _analyze(str(ROOT / "samples" / "rag_system.yaml"))
    assert [m.id for m in a.mitigations] == [m.id for m in b.mitigations]
    assert [p.id for p in a.attack_paths] == [p.id for p in b.attack_paths]
    assert a.mitigations, "expected rag_system to yield mitigations"


def test_stix_bundle_id_deterministic():
    """audit F044: the STIX bundle id must repeat across runs (was uuid4())."""
    import json

    from atms.reporting.stix import render_stix
    a = _analyze(str(ROOT / "samples" / "rag_system.yaml"))
    b = _analyze(str(ROOT / "samples" / "rag_system.yaml"))
    assert json.loads(render_stix(a))["id"] == json.loads(render_stix(b))["id"]


def test_sbom_serial_deterministic():
    """audit F043: the CycloneDX SBOM serialNumber must repeat across runs."""
    import json

    from atms.reporting.sbom_export import render_sbom_cdx
    a = _analyze(str(ROOT / "samples" / "rag_system.yaml"))
    b = _analyze(str(ROOT / "samples" / "rag_system.yaml"))
    assert json.loads(render_sbom_cdx(a))["serialNumber"] == json.loads(render_sbom_cdx(b))["serialNumber"]


def test_threat_references_are_sorted():
    """audit F045: threat.references must be sorted (was list(set(...)),
    whose iteration order varied across processes)."""
    a = _analyze(str(ROOT / "samples" / "rag_system.yaml"))
    for t in a.threats:
        assert t.references == sorted(t.references), f"{t.id} references not sorted: {t.references}"


def test_generated_at_honors_source_date_epoch(monkeypatch):
    """audit F042: SOURCE_DATE_EPOCH pins generated_at so the primary
    deliverable can be byte-identical across runs."""
    from datetime import UTC, datetime
    monkeypatch.setenv("SOURCE_DATE_EPOCH", "1700000000")
    a = _analyze(str(ROOT / "samples" / "rag_system.yaml"))
    assert a.generated_at == datetime.fromtimestamp(1700000000, UTC)


def test_stable_id_contract():
    assert stable_id("MIT", "x", "y") == stable_id("MIT", "x", "y")
    assert stable_id("MIT", "x").startswith("MIT-")
    assert len(stable_id("MIT", "x")) == len("MIT-") + 8
    assert stable_id("MIT", "a", "b") != stable_id("MIT", "b", "a")
    assert stable_id("MIT", "x") != stable_id("REC", "x")


def test_fallback_threats_deterministic_and_marked():
    from atms.engines.stride_ai import _fallback_threats

    comp = Component(id="x", name="Mystery", type="other")
    out = _fallback_threats(comp)
    assert len(out) == 3
    assert {t.stride_ai[0] for t in out} == {
        "Spoofing", "Tampering", "Information_Disclosure"}
    assert all(t.references == ["needs_review"] for t in out)
    # Deterministic: a second call yields identical IDs.
    assert [t.id for t in out] == [t.id for t in _fallback_threats(comp)]
