"""Executive-summary report (v0.18.10 Cycle Z).

A one-page leadership-friendly view of a threat-model run. The full
HTML report is comprehensive but ~100 KB and visually dense; CISOs
and board reviewers want a one-page snapshot:

  - System overview (name, components, deployment stage)
  - Headline metrics (threats, critical/high count, ALE range)
  - Top 5 threats by risk score
  - Top 5 mitigations by priority
  - Trust-boundary count + crosses
  - 1-paragraph narrative summary

Pure-Python template (string-formatted, no Jinja) so the file is
self-contained and easy to embed. Output is HTML that prints
cleanly to PDF if needed.
"""

from __future__ import annotations

from collections import Counter

from ..models import ThreatModel

_HTML_TEMPLATE = """<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Threat-model executive summary — {system_name}</title>
<style>
  body {{
    font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif;
    max-width: 900px; margin: 32px auto; padding: 0 24px;
    color: #0e1116; background: #ffffff; line-height: 1.55;
  }}
  h1 {{ font-size: 26px; margin: 0 0 4px 0; }}
  h1 small {{ font-weight: 400; color: #6e7681; font-size: 14px; }}
  h2 {{ font-size: 16px; text-transform: uppercase; letter-spacing: 0.06em;
        color: #57606a; border-bottom: 1px solid #d0d7de; padding-bottom: 4px;
        margin-top: 28px; }}
  .lead {{ color: #424a53; margin: 8px 0 18px 0; }}
  .metric-grid {{
    display: grid; grid-template-columns: repeat(auto-fit, minmax(150px, 1fr));
    gap: 12px; margin: 14px 0;
  }}
  .metric {{
    background: #f6f8fa; border: 1px solid #d0d7de; border-radius: 8px;
    padding: 12px 14px;
  }}
  .metric .v {{ font-size: 24px; font-weight: 700; }}
  .metric .k {{ font-size: 11px; color: #6e7681; text-transform: uppercase;
                letter-spacing: 0.05em; margin-bottom: 4px; }}
  .metric.critical .v {{ color: #cf222e; }}
  .metric.high .v {{ color: #d1242f; }}
  .metric.medium .v {{ color: #bf8700; }}
  table {{ width: 100%; border-collapse: collapse; font-size: 13px;
           margin: 10px 0; }}
  th, td {{ text-align: left; padding: 6px 10px; border-bottom: 1px solid #d0d7de; }}
  th {{ background: #f6f8fa; }}
  .severity {{ display: inline-block; padding: 2px 8px; border-radius: 999px;
               font-size: 10px; font-weight: 700; text-transform: uppercase;
               color: white; }}
  .sev-critical {{ background: #cf222e; }}
  .sev-high     {{ background: #d1242f; }}
  .sev-medium   {{ background: #bf8700; }}
  .sev-low      {{ background: #2da44e; }}
  .sev-info     {{ background: #6e7681; }}
  .narrative {{ background: #fff8c5; border: 1px solid #d4a72c;
                border-radius: 8px; padding: 14px 18px; font-size: 14px; }}
  footer {{ color: #6e7681; font-size: 12px; margin-top: 32px;
            padding-top: 12px; border-top: 1px solid #d0d7de; }}
  @media print {{ body {{ max-width: 100%; margin: 0; }} }}
</style>
</head>
<body>

<h1>{system_name} <small>threat-model executive summary</small></h1>
<p class="lead">{system_desc}</p>

<div class="narrative">{narrative}</div>

<h2>Headline metrics</h2>
<div class="metric-grid">
  <div class="metric"><div class="k">Components</div><div class="v">{n_components}</div></div>
  <div class="metric"><div class="k">Dataflows</div><div class="v">{n_dataflows}</div></div>
  <div class="metric"><div class="k">Trust boundaries</div><div class="v">{n_boundaries}</div></div>
  <div class="metric"><div class="k">Threats (active)</div><div class="v">{n_threats}</div></div>
  <div class="metric critical"><div class="k">Critical</div><div class="v">{n_critical}</div></div>
  <div class="metric high"><div class="k">High</div><div class="v">{n_high}</div></div>
  <div class="metric medium"><div class="k">Medium</div><div class="v">{n_medium}</div></div>
  <div class="metric"><div class="k">Annual loss expectancy</div><div class="v" style="font-size:16px;">{ale_range}</div></div>
  <div class="metric"><div class="k">Mitigations</div><div class="v">{n_mitigations}</div></div>
</div>

<h2>Top 5 threats by risk</h2>
{threats_table}

<h2>Top 5 mitigation priorities</h2>
{mitigations_table}

<h2>Coverage summary</h2>
<p>STRIDE for AI: {stride_breakdown}<br>
OWASP LLM: {owasp_pct}% &nbsp;·&nbsp;
MITRE ATLAS techniques cited: {atlas_count} &nbsp;·&nbsp;
Frameworks referenced: {framework_count}</p>

<footer>
Generated by ATMS v{tool_version}. Methodology: {methodology}.
Full report (HTML, STIX, SARIF, Navigator, CSV) generated alongside this summary.
</footer>
</body>
</html>
"""


def _table_threats(threats: list) -> str:
    # audit F013/F014: the headline metrics exclude closed dispositions
    # (mitigated / false_positive / duplicate), so the 'Top 5 threats by risk'
    # table must too -- otherwise a triaged-away CRITICAL is presented as the
    # #1 risk on a one-pager that simultaneously reports 'Critical: 0'.
    from ..models import is_closed
    active = [t for t in threats if not is_closed(t.disposition)]
    rows = ["<table><thead><tr><th>ID</th><th>Severity</th><th>Title</th><th>L × I</th><th>Risk</th></tr></thead><tbody>"]
    for t in sorted(active, key=lambda x: x.risk_score, reverse=True)[:5]:
        rows.append(
            f"<tr><td><code>{_esc(t.id)}</code></td>"
            f"<td><span class='severity sev-{_esc(t.severity)}'>{_esc(t.severity)}</span></td>"
            f"<td>{_esc(t.title)}</td>"
            f"<td>{t.likelihood} × {t.impact}</td>"
            f"<td><strong>{t.risk_score}</strong>/100</td></tr>"
        )
    rows.append("</tbody></table>")
    return "".join(rows)


def _table_mitigations(mitigations: list, summary: dict) -> str:
    priority_ids = summary.get("priority_mitigation_ids") or []
    by_id = {m.id: m for m in mitigations}
    rows = ["<table><thead><tr><th>ID</th><th>Title</th><th>Effort</th><th>Reduces</th><th>Threats addressed</th></tr></thead><tbody>"]
    for mid in priority_ids[:5]:
        m = by_id.get(mid)
        if not m:
            continue
        rows.append(
            f"<tr><td><code>{_esc(m.id)}</code></td>"
            f"<td>{_esc(m.title)}</td>"
            f"<td>{_esc(m.effort)}</td>"
            f"<td>{m.risk_reduction}/5</td>"
            f"<td>{len(m.addresses_threat_ids)}</td></tr>"
        )
    rows.append("</tbody></table>")
    return "".join(rows)


def _narrative(model: ThreatModel, n_critical: int, n_high: int) -> str:
    """One-paragraph executive narrative. Deterministic — derived from
    the summary stats, NOT generated by an LLM."""
    threat_count = len(model.threats)
    n_components = len(model.system.components)
    n_active = model.summary.get("threats_active", threat_count)
    n_closed = model.summary.get("threats_closed", 0)

    if n_critical >= 5 or n_high >= 20:
        posture = (
            "<strong>Posture: ELEVATED.</strong> Multiple critical / high-severity "
            "findings cluster on this system; recommend a focused remediation "
            "sprint before the next deployment milestone."
        )
    elif n_critical >= 1 or n_high >= 5:
        posture = (
            "<strong>Posture: ATTENTION.</strong> A small number of critical / high "
            "findings need owner assignment + a target close date. Most threats "
            "are medium-or-below."
        )
    else:
        posture = (
            "<strong>Posture: HEALTHY.</strong> No critical findings; medium-and-"
            "below findings can be tracked through the standard backlog."
        )

    carry_note = (
        f" {n_closed} threat(s) carry forward as closed from the prior run."
        if n_closed else ""
    )

    return (
        f"<strong>{_esc(model.system.name)}</strong> — analyzed {n_components} components "
        f"producing {threat_count} threats ({n_active} active). {posture}{carry_note}"
    )


def render_exec_summary(model: ThreatModel) -> str:
    """Render the executive-summary HTML for a ThreatModel.

    Self-contained — no external CSS or JS. Prints cleanly to PDF.
    Pure deterministic content derived from model.summary; no LLM
    call.
    """
    summary = model.summary
    sev = summary.get("severity_breakdown", {})
    n_critical = int(sev.get("critical", 0))
    n_high = int(sev.get("high", 0))
    n_medium = int(sev.get("medium", 0))

    # ALE range — format with thousands separators.
    ale = summary.get("ale") or {}
    ale_low = ale.get("ale_low_total") or 0
    ale_high = ale.get("ale_high_total") or 0
    if ale_high:
        ale_range = f"${ale_low:,.0f} – ${ale_high:,.0f}"
    else:
        ale_range = "—"

    # STRIDE breakdown text.
    stride_counts: Counter = Counter()
    for t in model.threats:
        for s in t.stride_ai or []:
            stride_counts[s] += 1
    stride_breakdown = " · ".join(
        f"{k} ({v})" for k, v in stride_counts.most_common(6)
    ) or "—"

    # OWASP-LLM coverage as percentage.
    owasp = summary.get("owasp_coverage") or []
    owasp_pct = int(round((len(owasp) / 10) * 100)) if owasp else 0

    atlas_count = len(summary.get("atlas_coverage") or [])
    framework_count = len(summary.get("compliance_frameworks") or [])

    # Tool version (read lazily to avoid circular imports).
    from .. import __version__

    return _HTML_TEMPLATE.format(
        system_name=_esc(model.system.name),
        system_desc=_esc(model.system.description or "(no description)"),
        narrative=_narrative(model, n_critical, n_high),
        n_components=len(model.system.components),
        n_dataflows=len(model.system.dataflows),
        n_boundaries=len(model.system.trust_boundaries),
        n_threats=summary.get("threats_active", len(model.threats)),
        n_critical=n_critical,
        n_high=n_high,
        n_medium=n_medium,
        ale_range=ale_range,
        n_mitigations=len(model.mitigations),
        threats_table=_table_threats(model.threats),
        mitigations_table=_table_mitigations(model.mitigations, summary),
        stride_breakdown=stride_breakdown,
        owasp_pct=owasp_pct,
        atlas_count=atlas_count,
        framework_count=framework_count,
        tool_version=__version__,
        methodology=summary.get("methodology", "stride-ai"),
    )


def _esc(s: str) -> str:
    """Minimal HTML escape for user-supplied strings."""
    return (
        str(s)
        .replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )


__all__ = ["render_exec_summary"]
