"""MITRE ATLAS Navigator JSON layer export.

Produces a JSON layer compatible with the ATLAS Navigator. Each
technique gets a score equal to the maximum DREAD-AI risk_score across
all threats that reference it. The layer can be loaded into
https://mitre-atlas.github.io/atlas-navigator/

In v0.14.3 we also emit a separate ATT&CK Enterprise / Cloud layer when
non-ATLAS techniques are referenced (returned as a multi-layer document
when the system is hybrid). Defaults to the ATLAS layer for backwards
compatibility — callers reading `json.loads(out)` see the same shape
they used to.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime

from ..models import ThreatModel


def _build_layer(name: str, domain: str, technique_scores: dict[str, float],
                  technique_threats: dict[str, list[str]],
                  attack_version: str, system_name: str, tool_version: str) -> dict:
    techniques = []
    for tech_id, score in sorted(technique_scores.items()):
        threat_list = technique_threats.get(tech_id, [])
        techniques.append({
            "techniqueID": tech_id,
            "score": round(score, 1),
            "color": "",
            "comment": (f"{len(threat_list)} threats: "
                        f"{', '.join(threat_list[:5])}"),
            "enabled": True,
            "metadata": [],
            "links": [],
            "showSubtechniques": False,
        })
    return {
        "name": name,
        "versions": {"attack": attack_version, "navigator": "v5", "layer": "4.5"},
        "domain": domain,
        "description": (
            f"Auto-generated by ATMS v{tool_version} on "
            f"{datetime.now(UTC).strftime('%Y-%m-%d')}. "
            "Scores reflect maximum DREAD-AI risk score across associated threats."
        ),
        "filters": {"platforms": ["AI", "ML", "GenAI", "Cloud", "Linux", "Windows", "Containers"]},
        "sorting": 3,
        "layout": {"layout": "side", "aggregateFunction": "max"},
        "hideDisabled": False,
        "techniques": techniques,
        "gradient": {"colors": ["#fbe0e0", "#a52a2a"], "minValue": 0, "maxValue": 100},
        "legendItems": [],
        "metadata": [
            {"name": "tool", "value": "ATMS"},
            {"name": "system", "value": system_name},
            {"name": "threats", "value": str(len(technique_threats))},
        ],
        "showTacticRowBackground": True,
        "tacticRowBackground": "#1f2630",
        "selectTechniquesAcrossTactics": True,
    }


def render_navigator(model: ThreatModel) -> str:
    """Return a Navigator layer JSON.

    Single-dict shape preserved for backwards compatibility. When the
    model has at least one ATLAS technique we emit the ATLAS layer
    (the historical default — what every existing consumer expects).
    For cloud-only / IT-only systems with zero ATLAS techniques but
    non-zero ATT&CK Enterprise / Cloud techniques (e.g. a Terraform
    ingest of a SCADA / database stack), we silently switch the
    layer's domain to `enterprise-attack` and populate from
    `attack_enterprise + attack_cloud` so the file is still useful.
    Otherwise an empty Navigator layer would mislead the reviewer.
    """
    atlas_scores: dict[str, float] = {}
    atlas_threats: dict[str, list[str]] = {}
    enterprise_scores: dict[str, float] = {}
    enterprise_threats: dict[str, list[str]] = {}
    for t in model.threats:
        for atlas_id in t.atlas_techniques:
            if atlas_id.startswith("AML."):
                atlas_scores[atlas_id] = max(atlas_scores.get(atlas_id, 0.0), t.risk_score)
                atlas_threats.setdefault(atlas_id, []).append(t.id)
        for tech_id in (t.attack_enterprise or []) + (t.attack_cloud or []):
            if tech_id and tech_id.startswith("T"):
                enterprise_scores[tech_id] = max(enterprise_scores.get(tech_id, 0.0), t.risk_score)
                enterprise_threats.setdefault(tech_id, []).append(t.id)

    # audit F016: emit BOTH layers for a hybrid AI+cloud system instead of
    # discarding the ATT&CK Enterprise/Cloud techniques whenever any ATLAS
    # technique exists. A single-domain system returns one layer (object); a
    # hybrid one returns a multi-layer document (array) -- both are valid
    # MITRE Navigator imports.
    layers = []
    if atlas_scores:
        layers.append(_build_layer(
            f"ATMS — {model.system.name}", "atlas",
            atlas_scores, atlas_threats, "v15",
            model.system.name, model.tool_version,
        ))
    if enterprise_scores:
        layers.append(_build_layer(
            f"ATMS — {model.system.name} (ATT&CK)", "enterprise-attack",
            enterprise_scores, enterprise_threats, "v15",
            model.system.name, model.tool_version,
        ))
    if not layers:
        # No mapped techniques at all -- keep the file useful with an (empty)
        # ATLAS layer rather than emitting nothing.
        layers.append(_build_layer(
            f"ATMS — {model.system.name}", "atlas",
            atlas_scores, atlas_threats, "v15",
            model.system.name, model.tool_version,
        ))
    out = layers[0] if len(layers) == 1 else layers
    return json.dumps(out, indent=2)
